# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"
mac: "my_mac"
agent: "sra"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "sra_learner"
double_q: True
mixer: "qmix"
n_roles: 4
mixing_embed_dim: 32
hidden_dim: 32
embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
lambda_d: 0.001
lambda_h: 0.001

name: "sra"
